server {
    listen 80;
    client_max_body_size 20m;
    root /usr/share/nginx/html;

    location /api/ { proxy_pass http://api:8000; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto $scheme; proxy_read_timeout 300s; }
    # QuickBooks Web Connector SOAP endpoint
    location /qbwc  { proxy_pass http://api:8000; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto $scheme; proxy_read_timeout 300s; }

    location / { try_files $uri $uri/ /index.html; }
}
